# Generated by Django 5.1.7 on 2025-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('ne_lat', models.FloatField()),
                ('ne_lng', models.FloatField()),
                ('sw_lat', models.FloatField()),
                ('sw_lng', models.FloatField()),
                ('results', models.JSONField()),
            ],
        ),
    ]
