# Generated by Django 5.1.7 on 2025-04-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('ne_lat', models.FloatField()),
                ('ne_lng', models.FloatField()),
                ('sw_lat', models.FloatField()),
                ('sw_lng', models.FloatField()),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('frequency_interval', models.IntegerField(default=1)),
                ('frequency_unit', models.CharField(default='hours', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('normalized_url', models.CharField(max_length=255)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scraper.search')),
            ],
            options={
                'unique_together': {('search', 'normalized_url')},
            },
        ),
    ]
