# Generated by Django 5.1.7 on 2025-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('ne_lat', models.FloatField()),
                ('ne_lng', models.FloatField()),
                ('sw_lat', models.FloatField()),
                ('sw_lng', models.FloatField()),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
