# Generated by Django 5.1.7 on 2025-03-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_search_results_searchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='normalized_url',
            field=models.CharField(max_length=255),
        ),
    ]
