# Generated by Django 5.1.7 on 2025-03-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_searchresult_normalized_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together={('search', 'normalized_url')},
        ),
    ]
